export const ADD_ITEM = "ADD_ITEM"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const ADD_QUANTITY = "ADD_QUANTITY"
export const REMOVE_QUANTITY = "REMOVE_QUANTITY"
export const SET_TIME = "SET_TIME"
export const UPDATE_TIME = "UPDATE_TIME"
export const ADD_ORDER_NUMBER = "ADD_ORDER_NUMBER"
export const LOG_IN = "LOG_IN"
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE"
export const SAVE_TO_ORDER_HISTORY = "SAVE_TO_ORDER_HISTORY"
export const INC_QUANTITY = "INC_QUANTITY"
export const SAVE_TO_TOTAL_PRICE = "SAVE_TO_TOTAL_PRICE"
export const RESET = "RESET"
export const SET_ORDER_DATE = "SET_ORDER_DATE"


